# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718a6518dee5df1ea6101158a64d11c50afea385a2495c939a183805068bb2a7236a0d5d134a4f3bc8cab1b905759a3e552e132bff58be65d24ce2a06b3f4542

test:
  secret_key_base: a2ab7352cc6209b79d669174b08efef758359d80760ead8260457a001c5f355823bf7e19ae6690898c3146309d2d2f96ae34d440328ef3cb6ae029b7c54b5fe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
